# Generated by Django 4.2.4 on 2023-08-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visits',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
