# Generated by Django 4.2.4 on 2023-08-18 03:17

import app_blog.models
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_post_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_drop',
            field=ckeditor.fields.RichTextField(blank=True, null=True, validators=[app_blog.models.Post.validate_title_drop]),
        ),
    ]
