# Generated by Django 4.2.4 on 2023-08-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0007_alter_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='is_visible',
        ),
    ]
